language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install python-numpy python-matplotlib python-mpltoolkits.basemap 
install:
  - python setup.py install 
script: cd test; ./test.sh
