language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
before_install:
  - sudo apt-get install cython libhdf4-dev libhdfeos-dev python-numpy python-matplotlib python-mpltoolkits.basemap 
install:
  - python setup.py install 
script: cd test; ./test.sh
